export { scanFileFromBuffer } from './modules/scanFileFromBuffer'
export { scanFileFromLink } from './modules/scanFileFromLink'
export { scanFileFromLocation } from './modules/scanFileFromLocation'
export { scanFileFromStream } from './modules/scanFileFromStream'
export { scanLink } from './modules/scanLink'