// export { default as scanFileFromBuffer } from './modules/scanFileFromBuffer'
// export { default as scanFileFromLink } from './modules/scanFileFromLink'
// export { default as scanFileFromLocation } from './modules/scanFileFromLocation'
// export { default as scanFileFromStream } from './modules/scanFileFromStream'
// export { default as scanLink } from './modules/scanLink'
export { default as isMalware } from './modules/isMalware'
export { default as isNSFW } from './modules/isNSFW'